#ifndef LGBAT_TOPICIDS_H
#define LGBAT_TOPICIDS_H



// Command Topic IDs
#define CFE_MISSION_LGBAT_CMD_TOPICID          0xC6
#define CFE_MISSION_LGBAT_WAKEUP_TOPICID       0xC7
#define CFE_MISSION_LGBAT_SEND_BCN_TOPICID     0xC8

// Telemetry Topic IDs
#define CFE_MISSION_LGBAT_FULLDATA_TLM_TOPICID 0xC6
#define CFE_MISSION_LGBAT_REPORT_TOPICID       0xC7
#define CFE_MISSION_LGBAT_BCN_TLM_TOPICID      0xC8
#define CFE_MISSION_LGBAT_CRITICAL_TOPICID     0xC9

#endif /* LGBAT_TOPICIDS_H */
