#ifndef LGBAT_MSGIDS_H
#define LGBAT_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "lgbat_topicids.h"

// PAYUEL_LGBAT Message ID definitions


// Command MIDs (Ground/SCH -> OBC)
#define LGBAT_CMD_MID      CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_LGBAT_CMD_TOPICID)
#define LGBAT_SEND_HK_MID  CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_LGBAT_SEND_HK_TOPICID)
#define LGBAT_SEND_BCN_MID CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_LGBAT_SEND_BCN_TOPICID)

// Telemetry MIDs (OBC -> Ground)
#define LGBAT_HK_TLM_MID     CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_LGBAT_HK_TLM_TOPICID)
#define LGBAT_REPORT_TLM_MID CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_LGBAT_REPORT_TOPICID)
#define LGBAT_BCN_TLM_MID    CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_LGBAT_BCN_TLM_TOPICID)

#endif // LGBAT_MSGIDS_H
