#ifndef SP_APP_VERSION_H
#define SP_APP_VERSION_H

#define SP_APP_BUILD_NUMBER 1
#define SP_APP_BUILD_BASELINE "FSW_BASELINE-rc1"
#define SP_APP_BUILD_CODENAME "FSW_BASELINE"

#define SP_APP_LAST_OFFICIAL "v1.1.0"

#define SP_APP_STR_HELPER(x) #x
#define SP_APP_STR(x) SP_APP_STR_HELPER(x)

#define SP_APP_VERSION SP_APP_BUILD_BASELINE "+dev" SP_APP_STR(SP_APP_BUILD_NUMBER)

#define SP_APP_CFG_MAX_VERSION_STR_LEN 256

#endif