#ifndef PAYUEL_OBC_VERSION_H
#define PAYUEL_OBC_VERSION_H

#define PAYUEL_OBC_MAJOR_VERSION 1
#define PAYUEL_OBC_MINOR_VERSION 0
#define PAYUEL_OBC_REVISION      0

#define PAYUEL_OBC_STR_HELPER(x) #x
#define PAYUEL_OBC_STR(x) PAYUEL_OBC_STR_HELPER(x)

#define PAYUEL_OBC_VERSION "v" PAYUEL_OBC_STR(PAYUEL_OBC_MAJOR_VERSION) "." \
                              PAYUEL_OBC_STR(PAYUEL_OBC_MINOR_VERSION) "." \
                              PAYUEL_OBC_STR(PAYUEL_OBC_REVISION)

#define PAYUEL_OBC_CFG_MAX_VERSION_STR_LEN 256

#endif /* PAYUEL_OBC_VERSION_H */
