#ifndef PAYUZUT_MSGIDS_H
#define PAYUZUT_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "payuzut_topicids.h"

#define PAYUZUT_CMD_MID             CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUT_CMD_TOPICID)
#define PAYUZUT_SEND_HK_MID         CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUT_SEND_HK_TOPICID)
#define PAYUZUT_SEND_BCN_MID        CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUT_SEND_BCN_TOPICID)

#define PAYUZUT_REPORT_TLM_MID      CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUT_REPORT_TLM_TOPICID)
#define PAYUZUT_BCN_TLM_MID         CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUT_BCN_TLM_TOPICID)

#endif
