#ifndef PAYUEL_OBC_EVENTS_H
#define PAYUEL_OBC_EVENTS_H

#define PAYUEL_OBC_RESERVED_EID       0
#define PAYUEL_OBC_INIT_INF_EID       1
#define PAYUEL_OBC_CC_ERR_EID         2
#define PAYUEL_OBC_NOOP_INF_EID       3
#define PAYUEL_OBC_RESET_INF_EID      4
#define PAYUEL_OBC_MID_ERR_EID        5
#define PAYUEL_OBC_CMD_LEN_ERR_EID    6
#define PAYUEL_OBC_PIPE_ERR_EID       7
#define PAYUEL_OBC_VALUE_INF_EID      8
#define PAYUEL_OBC_CR_PIPE_ERR_EID    9
#define PAYUEL_OBC_SUB_BCN_ERR_EID   10
#define PAYUEL_OBC_SUB_CMD_ERR_EID   11
#define PAYUEL_OBC_TABLE_REG_ERR_EID 12
#define PAYUEL_OBC_TX_ERR_EID        13
#define PAYUEL_OBC_COMMAND_ERR_EID   14
#define PAYUEL_OBC_FILE_OPEN_ERR_EID 15
#define PAYUEL_OBC_FILE_WRITE_ERR_EID 16
#define PAYUEL_OBC_CRC_ERR_EID       17
#define PAYUEL_OBC_RX_LEN_ERR_EID    18
#define PAYUEL_OBC_STATUS_ERR_EID    19
#define PAYUEL_OBC_MUTEX_ERR_EID     20
#define PAYUEL_OBC_CHILD_INIT_ERR_EID 21
#define PAYUEL_OBC_CHILD_INIT_INF_EID 22
#define PAYUEL_OBC_CHILD_BUSY_ERR_EID 23
#define PAYUEL_OBC_DOWNLOAD_REQ_INF_EID 24
#define PAYUEL_OBC_DOWNLOAD_DONE_INF_EID 25
#define PAYUEL_OBC_FILE_CRC_ERR_EID  26
#define PAYUEL_OBC_FILE_RENAME_ERR_EID 27
#define PAYUEL_OBC_FILE_READ_ERR_EID 28
#define PAYUEL_OBC_CHILD_TERM_ERR_EID 29

#endif /* PAYUEL_OBC_EVENTS_H */
