/**
 * @file
 *
 * Define PAY UZURO CAM App Events IDs
 */
#ifndef PAYUZUC_EVENTIDS_H
#define PAYUZUC_EVENTIDS_H

#define PAYUZUC_RESERVED_EID    0
#define PAYUZUC_INIT_INF_EID    1
#define PAYUZUC_CC_ERR_EID      2
#define PAYUZUC_NOOP_INF_EID    3
#define PAYUZUC_RESET_INF_EID   4
#define PAYUZUC_MID_ERR_EID     5
#define PAYUZUC_CMD_LEN_ERR_EID 6
#define PAYUZUC_PIPE_ERR_EID    7
#define PAYUZUC_SUB_HK_ERR_EID  10
#define PAYUZUC_SUB_CMD_ERR_EID 11

#endif /* PAYUZUC_EVENTIDS_H*/