/**
 * @file
 *   MEOW Application Topic IDs
 */
#ifndef MEOW_TOPICIDS_H
#define MEOW_TOPICIDS_H

#include "meow_topicid_values.h"

#define MEOW_MISSION_CMD_TOPICID             MEOW_MISSION_TIDVAL(CMD)
#define DEFAULT_MEOW_MISSION_CMD_TOPICID     0x82

#define MEOW_MISSION_SEND_HK_TOPICID         MEOW_MISSION_TIDVAL(SEND_HK)
#define DEFAULT_MEOW_MISSION_SEND_HK_TOPICID 0x83

#define MEOW_MISSION_HK_TLM_TOPICID          MEOW_MISSION_TIDVAL(HK_TLM)
#define DEFAULT_MEOW_MISSION_HK_TLM_TOPICID  0x84

#define MEOW_MISSION_REPORT_TLM_TOPICID      MEOW_MISSION_TIDVAL(REPORT_TLM)
#define DEFAULT_MEOW_MISSION_REPORT_TLM_TOPICID  0x85

#endif /* MEOW_TOPICIDS_H */
