/**
 * @file
 *   PAY UZURO CAM APP Application Topic IDs
 */
#ifndef PAYUZUC_TOPICIDS_H
#define PAYUZUC_TOPICIDS_H

/**
 * TOPIC definition
 */
#define CFE_MISSION_PAYUZUC_CMD_TOPICID             0x30
#define CFE_MISSION_PAYUZUC_SEND_HK_TOPICID         0x31
#define CFE_MISSION_PAYUZUC_SEND_BCN_TOPICID        0x32

#define CFE_MISSION_PAYUZUC_HK_TLM_TOPICID          0x30
#define CFE_MISSION_PAYUZUC_BCN_TLM_TOPICID         0x31
#define CFE_MISSION_PAYUZUC_REPORT_TOPICID          0x32

#endif