/**
 * @file
 *   PAY UZURO CAM Application Message IDs
 */
#ifndef PAYUZUC_MSGIDS_H
#define PAYUZUC_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "payuzuc_topicids.h"

#define PAYUZUC_CMD_MID             CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUC_CMD_TOPICID)
#define PAYUZUC_SEND_HK_MID         CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUC_SEND_HK_TOPICID)

#define PAYUZUC_HK_TLM_MID          CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUC_HK_TLM_TOPICID)

/**
 * KissCAM Image Data MID
 */
#define PAYUZUC_REPORT_TLM_MID                 CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUC_REPORT_TOPICID)
// #define PAYUZUC_THUMBNAIL_IMG_MID       CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUZUC_TUMBNAIL_IMG_TOPICID)

#endif