#ifndef SP_EVENTS_H
#define SP_EVENTS_H

#define SP_RESERVED_EID 0
#define SP_INIT_INF_EID 1
#define SP_CC_ERR_EID 2
#define SP_NOOP_INF_EID 3
#define SP_RESET_INF_EID 4
#define SP_DEPLOY_INF_EID 5
#define SP_DEPLOY_CMD_INF_EID 6
#define SP_MID_ERR_EID 7
#define SP_CMD_LEN_ERR_EID 8
#define SP_PIPE_ERR_EID 9
#define SP_VALUE_INF_EID 10
#define SP_CR_PIPE_ERR_EID 11
#define SP_SUB_CMD_ERR_EID 12
#define SP_SUB_DEP_ERR_EID 13
#define SP_TABLE_REG_ERR_EID 14

#endif