#ifndef SP_APP_EVENTS_H
#define SP_APP_EVENTS_H

#define SP_APP_RESERVED_EID 0
#define SP_APP_INIT_INF_EID 1
#define SP_APP_CC_ERR_EID 2
#define SP_APP_NOOP_INF_EID 3
#define SP_APP_RESET_INF_EID 4
#define SP_APP_DEPLOY_INF_EID 5
#define SP_APP_DEPLOY_CMD_INF_EID 6
#define SP_APP_MID_ERR_EID 7
#define SP_APP_CMD_LEN_ERR_EID 8
#define SP_APP_PIPE_ERR_EID 9
#define SP_APP_VALUE_INF_EID 10
#define SP_APP_CR_PIPE_ERR_EID 11
#define SP_APP_SUB_CMD_ERR_EID 12
#define SP_APP_SUB_DEP_ERR_EID 13
#define SP_APP_TABLE_REG_ERR_EID 14

#endif