/**
 * @file  GPS application message IDs
 */
#ifndef DEFAULT_GPS_MSGIDS_H
#define DEFAULT_GPS_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "default_gps_topicids.h"

#define GPS_CMD_MID        CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_GPS_CMD_TOPICID)
#define GPS_SEND_HK_MID    CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_GPS_SEND_HK_TOPICID)
#define GPS_HK_TLM_MID     CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_HK_TLM_TOPICID)

/** Named as the RPT table entry names it; see apps/rpt/fsw/tables/rpt_tbl.c. */
#define GPS_REPORT_TLM_MID CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_REPORT_TLM_TOPICID)

/** OEM7 stored logs. */
#define GPS_OEM_BESTXYZ_TLM_MID    CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_OEM_BESTXYZ_TLM_TOPICID)
#define GPS_OEM_BESTPOS_TLM_MID    CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_OEM_BESTPOS_TLM_TOPICID)
#define GPS_OEM_RANGE_TLM_MID      CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_OEM_RANGE_TLM_TOPICID)
#define GPS_OEM_TIME_TLM_MID       CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_OEM_TIME_TLM_TOPICID)
#define GPS_OEM_CLOCKMODEL_TLM_MID CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_OEM_CLOCKMODEL_TLM_TOPICID)
#define GPS_OEM_HWMONITOR_TLM_MID  CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_OEM_HWMONITOR_TLM_TOPICID)
#define GPS_OEM_RXSTATUS_TLM_MID   CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_OEM_RXSTATUS_TLM_TOPICID)
#define GPS_OEM_SATVIS2_TLM_MID    CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_GPS_OEM_SATVIS2_TLM_TOPICID)

#endif
