/**
 * @file
 *   FTP Application Message IDs
 */
#ifndef FTP_MSGIDS_H
#define FTP_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "ftp_topicids.h"

/**
 * Definition of CMD MID
 */
#define FTP_CMD_MID         CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_FTP_CMD_TOPICID)
#define FTP_SEND_BCN_MID    CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_FTP_SEND_BCN_TOPICID)
#define FTP_SEND_HK_MID     CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_FTP_SEND_HK_TOPICID)

/**
 * Definition of TLM MID
 */
#define FTP_BCN_TLM_MID     CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_FTP_BCN_TLM_TOPICID)
#define FTP_HK_TLM_MID      CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_FTP_HK_TLM_TOPICID)
#define FTP_FILE_MID        CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_FTP_FILE_TOPICID)
#define FTP_REPORT_TLM_MID  CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_FTP_REPORT_TLM_TOPICID)

#endif