#ifndef EO_TOPICIDS_H
#define EO_TOPICIDS_H


#define CFE_MISSION_EO_CMD_TOPICID         0x90
#define CFE_MISSION_EO_SEND_BCN_TOPICID    0x91
#define CFE_MISSION_EO_WAKEUP_TOPICID      0x92

#define CFE_MISSION_EO_BCN_TLM_TOPICID      0x90
#define CFE_MISSION_EO_REPORT_TOPICID       0x91
#define CFE_MISSION_EO_COMMISSION_TOPICID   0x92

#endif