/**
 * @file
 *
 * Define PAY UZURO THRUSTER App Events IDs
 */
#ifndef PAYUZUT_EVENTIDS_H
#define PAYUZUT_EVENTIDS_H

#define PAYUZUT_RESERVED_EID    0
#define PAYUZUT_INIT_INF_EID    1
#define PAYUZUT_CC_ERR_EID      2
#define PAYUZUT_NOOP_INF_EID    3
#define PAYUZUT_RESET_INF_EID   4
#define PAYUZUT_MID_ERR_EID     5
#define PAYUZUT_CMD_LEN_ERR_EID 6
#define PAYUZUT_PIPE_ERR_EID    7
#define PAYUZUT_SUB_HK_ERR_EID  10
#define PAYUZUT_SUB_CMD_ERR_EID 11


#define PAYUZUT_SEND_HK_INF_EID 23

#endif /* PAYUZUT_EVENTIDS_H*/