#ifndef SP_APP_INTERNAL_CFG_H
#define SP_APP_INTERNAL_CFG_H

#define SP_APP_PIPE_DEPTH 32
#define SP_APP_PIPE_NAME "SP_APP_CMD_PIPE"

#define SP_APP_NUMBER_OF_TABLES 1

#define SP_APP_TABLE_OUT_OF_RANGE_ERR_CODE -1

#define SP_APP_TBL_ELEMENT_1_MAX 10

#endif