#ifndef SP_TOPICIDS_H
#define SP_TOPICIDS_H

#define CFE_MISSION_SP_CMD_TOPICID          0x58
#define CFE_MISSION_SP_SEND_BCN_TOPICID     0x59

#define CFE_MISSION_SP_BCN_TLM_TOPICID      0x58
#define CFE_MISSION_SP_REPORT_TLM_MID       0x59

#endif