#ifndef SP_APP_MSGIDS_H
#define SP_APP_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "sp_topicids.h"

#define SP_APP_CMD_MID          CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_SP_APP_CMD_TOPICID)
#define SP_APP_SEND_BCN_MID     CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_SP_APP_SEND_BCN_TOPICID)

#define SP_APP_BCN_TLM_MID      CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_SP_APP_BCN_TLM_TOPICID)

#endif