#ifndef SP_MSGIDS_H
#define SP_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "sp_topicids.h"

/* Command MIDs */
#define SP_CMD_MID      CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_SP_CMD_TOPICID)
#define SP_SEND_BCN_MID CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_SP_SEND_BCN_TOPICID)
#define SP_SEND_HK_MID  CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_SP_SEND_HK_TOPICID)

/* Telemetry MIDs */
#define SP_BCN_TLM_MID    CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_SP_BCN_TLM_TOPICID)
#define SP_HK_TLM_MID     CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_SP_HK_TLM_TOPICID)
#define SP_REPORT_TLM_MID CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_SP_REPORT_TLM_MID)

#endif