/**
 * @file
 *   BATT Application Message IDs
 */
#ifndef BATT_MSGIDS_H
#define BATT_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "batt_topicids.h"

#define BATT_CMD_MID     CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_BATT_CMD_TOPICID)
#define BATT_SEND_HK_MID CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_BATT_SEND_HK_TOPICID)
#define BATT_HK_TLM_MID  CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_BATT_HK_TLM_TOPICID)

#endif
