#ifndef MISSION_TOPICIDS_H
#define MISSION_TOPICIDS_H

#define CFE_MISSION_MISSION_CMD_TOPICID       0x28
#define CFE_MISSION_MISSION_SEND_BCN_TOPICID  0x29
#define CFE_MISSION_MISSION_SEND_HK_TOPICID   0x2A

#define CFE_MISSION_MISSION_BCN_TLM_TOPICID      0x28
#define CFE_MISSION_MISSION_HK_TLM_TOPICID       0x29
#define CFE_MISSION_MISSION_REPORT_TLM_TOPICID   0x2A

#endif
