#ifndef MISSION_MSGIDS_H
#define MISSION_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "mission_topicids.h"

/**
 * For Telecommand handling
 */
#define MISSION_SET_COMPLETE_MID    CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_MISSION_SET_COMPLETE_TOPICID)
#define MISSION_SEND_HK_MID         CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_MISSION_SEND_HK_TOPICID)
#define MISSION_READ_LEOP_FILE_MID  CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_MISSION_READ_LEOP_FILE_TOPICID)

/**
 * For Telemetry publishing
 */
#define MISSION_HK_TLM_MID          CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_MISSION_HK_TLM_TOPICID)
#define MISSION_REPORT_TLM_MID      CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_MISSION_REPORT_TLM_TOPICID)

#endif
