#ifndef MISSION_TOPICIDS_H
#define MISSION_TOPICIDS_H

#define CFE_MISSION_MISSION_CMD_TOPICID       0x90
#define CFE_MISSION_MISSION_SEND_BCN_TOPICID  0x91
#define CFE_MISSION_MISSION_WAKEUP_TOPICID    0x92
#define CFE_MISSION_MISSION_SEND_HK_TOPICID   0x93

#define CFE_MISSION_MISSION_BCN_TLM_TOPICID      0x90
#define CFE_MISSION_MISSION_HK_TLM_TOPICID       0x93

#endif
