#ifndef MISSION_TOPICIDS_H
#define MISSION_TOPICIDS_H

#define CFE_MISSION_MISSION_SET_COMPLETE_TOPICID  0x91
#define CFE_MISSION_MISSION_WAKEUP_TOPICID    0x92
#define CFE_MISSION_MISSION_SEND_HK_TOPICID   0x93
#define CFE_MISSION_MISSION_READ_LEOP_FILE_TOPICID 0x99

#define CFE_MISSION_MISSION_HK_TLM_TOPICID       0x93
#define CFE_MISSION_MISSION_REPORT_TLM_TOPICID   0x92

#endif
