/* Auto-Generated file. Never change this code! */
#ifndef CFE_SRL_ERROR_H
#define CFE_SRL_ERROR_H

#include "cfe_usr_error_macro.h"

/**
 * Early Init error define
 */
#define CFE_SRL_I2C1_INIT_ERR		CFE_SERIAL_ERROR(90)
#define CFE_SRL_RS485_INIT_ERR		CFE_SERIAL_ERROR(91)
#define CFE_SRL_SPIO_INIT_ERR		CFE_SERIAL_ERROR(92)
#define CFE_SRL_CAN0_INIT_ERR		CFE_SERIAL_ERROR(93)
#define CFE_SRL_I2C2_INIT_ERR		CFE_SERIAL_ERROR(94)
#define CFE_SRL_RS422_INIT_ERR		CFE_SERIAL_ERROR(95)
#define CFE_SRL_UART_INIT_ERR		CFE_SERIAL_ERROR(96)
#define CFE_SRL_SP_IN_INIT_ERR		CFE_SERIAL_ERROR(97)
#define CFE_SRL_LTRX_EN_INIT_ERR		CFE_SERIAL_ERROR(98)
#define CFE_SRL_DEP1_EN_INIT_ERR		CFE_SERIAL_ERROR(99)
#define CFE_SRL_DEP2_EN_INIT_ERR		CFE_SERIAL_ERROR(100)
#define CFE_SRL_STX_EN_INIT_ERR		CFE_SERIAL_ERROR(101)
#define CFE_SRL_ADCS_EN_INIT_ERR		CFE_SERIAL_ERROR(102)
#define CFE_SRL_ADCS_BOOT_INIT_ERR		CFE_SERIAL_ERROR(103)


#endif /* CFE_SRL_ERROR_H */