#ifndef PAYUEL_OBC_MSGIDS_H
#define PAYUEL_OBC_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "payuel_obc_topicids.h"

#define PAYUEL_OBC_CMD_MID            CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUEL_OBC_CMD_TOPICID)
#define PAYUEL_OBC_SEND_BCN_MID       CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUEL_OBC_SEND_BCN_TOPICID)

#define PAYUEL_OBC_RPT_TLM_MID        CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUEL_OBC_RPT_TLM_TOPICID)
#define PAYUEL_OBC_OBC_BCN_TLM_MID    CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUEL_OBC_OBC_BCN_TLM_TOPICID)

#endif
