#ifndef PAYUEL_OBC_TOPICIDS_H
#define PAYUEL_OBC_TOPICIDS_H

#define CFE_MISSION_PAYUEL_OBC_CMD_TOPICID           0x9D
#define CFE_MISSION_PAYUEL_OBC_SEND_BCN_TOPICID      0x9E

#define CFE_MISSION_PAYUEL_OBC_RPT_TLM_TOPICID       0x9F
#define CFE_MISSION_PAYUEL_OBC_OBC_BCN_TLM_TOPICID   0xA0

#endif
