#ifndef PAYUEL_OBC_TOPICIDS_H
#define PAYUEL_OBC_TOPICIDS_H

#define CFE_MISSION_PAYUEL_OBC_CMD_TOPICID           0xC0
#define CFE_MISSION_PAYUEL_OBC_SEND_HK_TOPICID       0xC1
#define CFE_MISSION_PAYUEL_OBC_SEND_BCN_TOPICID      0xC2

#define CFE_MISSION_PAYUEL_OBC_HK_TLM_TOPICID        0xC0
#define CFE_MISSION_PAYUEL_OBC_RPT_TLM_TOPICID       0xC1
#define CFE_MISSION_PAYUEL_OBC_OBC_BCN_TLM_TOPICID   0xC2

#endif
