#ifndef PAYUEL_OBC_INTERNAL_CFG_H
#define PAYUEL_OBC_INTERNAL_CFG_H

#define PAYUEL_OBC_PIPE_DEPTH               32
#define PAYUEL_OBC_NUMBER_OF_TABLES         1
#define PAYUEL_OBC_TABLE_OUT_OF_RANGE_ERR_CODE -1
#define PAYUEL_OBC_TBL_ELEMENT_1_MAX        10

#define PAYUEL_OBC_CHILD_TASK_NAME          "PAYUEL_OBC_CHILD"
#define PAYUEL_OBC_CHILD_TASK_STACK_SIZE    16384
#define PAYUEL_OBC_CHILD_TASK_PRIORITY      205
#define PAYUEL_OBC_CHILD_SEM_NAME           "PAYUEL_OBC_SEM"
#define PAYUEL_OBC_CHILD_MUTEX_NAME         "PAY_OBC_CHILD_MUT"
#define PAYUEL_OBC_REPORT_MUTEX_NAME        "PAYUEL_OBC_RPT_MUT"
#define PAYUEL_OBC_HARDWARE_MUTEX_NAME      "PAYUEL_OBC_HW_MUT"

#define PAYUEL_OBC_DOWNLOAD_PATH_MAX        96
#define PAYUEL_OBC_FILE_CRC_BUFFER_SIZE     512

#endif
