#ifndef PAYUEL_CAM_VERSION_H
#define PAYUEL_CAM_VERSION_H

#define PAYUEL_CAM_MAJOR_VERSION 1
#define PAYUEL_CAM_MINOR_VERSION 0
#define PAYUEL_CAM_REVISION      0

#define PAYUEL_CAM_STR_HELPER(x) #x
#define PAYUEL_CAM_STR(x) PAYUEL_CAM_STR_HELPER(x)

#define PAYUEL_CAM_VERSION "v" PAYUEL_CAM_STR(PAYUEL_CAM_MAJOR_VERSION) "." \
                              PAYUEL_CAM_STR(PAYUEL_CAM_MINOR_VERSION) "." \
                              PAYUEL_CAM_STR(PAYUEL_CAM_REVISION)

#define PAYUEL_CAM_CFG_MAX_VERSION_STR_LEN 256

#endif /* PAYUEL_CAM_VERSION_H */
