#ifndef FTP_CLIENT_EVENTIDS_H
#define FTP_CLIENT_EVENTIDS_H

#define FTP_CLIENT_RESERVED_EID 0
#define FTP_CLIENT_INIT_INF_EID 1
#define FTP_CLIENT_CC_ERR_EID 2
#define FTP_CLIENT_MID_ERR_EID 3
#define FTP_CLIENT_CMD_LEN_ERR_EID 4
#define FTP_CLIENT_PIPE_ERR_EID 5
#define FTP_CLIENT_SUB_CMD_ERR_EID 6
#define FTP_CLIENT_UPLOAD_INF_EID 7
#define FTP_CLIENT_DOWNLOAD_INF_EID 8
#define FTP_CLIENT_TRANSFER_ERR_EID 9
#define FTP_CLIENT_NOOP_INF_EID 10

#endif
