#ifndef FTP_CLIENT_MSGIDS_H
#define FTP_CLIENT_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "ftp_client_topicids.h"

#define FTP_CLIENT_CMD_MID        CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_FTP_CLIENT_CMD_TOPICID)
#define FTP_CLIENT_REPORT_TLM_MID CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_FTP_CLIENT_REPORT_TLM_TOPICID)

#endif
