#ifndef _S5LAB_CONFIG_H_
#define _S5LAB_CONFIG_H_

#define S5LAB_CONF_CSP_DEFAULT_NODE     19
#define S5LAB_CONF_CSP_DEFAULT_TIMEOUT  1000

#define S5LAB_CONF_CSP_PORT_GENERAL     8
#define S5LAB_CONF_CSP_PORT_LOG         16
#define S5LAB_CONF_CSP_PORT_SCH         17
#define S5LAB_CONF_CSP_PORT_ROUTING     18
#define S5LAB_CONF_CSP_PORT_PARAMETERS  19
#define S5LAB_CONF_CSP_PORT_SHELL       20

#endif
