#ifndef PAYUEL_CAM_TOPICIDS_H
#define PAYUEL_CAM_TOPICIDS_H

#define CFE_MISSION_PAYUEL_CAM_CMD_TOPICID           0xC3
#define CFE_MISSION_PAYUEL_CAM_SEND_HK_TOPICID       0xC4
#define CFE_MISSION_PAYUEL_CAM_SEND_BCN_TOPICID      0xC5
#define CFE_MISSION_PAYUEL_CAM_HK_TLM_TOPICID        0xC3
#define CFE_MISSION_PAYUEL_CAM_RPT_TLM_TOPICID       0xC4
#define CFE_MISSION_PAYUEL_CAM_BCN_TLM_TOPICID       0xC5

#endif
