#ifndef PAYUEL_CAM_INTERNAL_CFG_H
#define PAYUEL_CAM_INTERNAL_CFG_H

#define PAYUEL_CAM_PIPE_DEPTH               32
#define PAYUEL_CAM_NUMBER_OF_TABLES         1
#define PAYUEL_CAM_TABLE_OUT_OF_RANGE_ERR_CODE -1
#define PAYUEL_CAM_TBL_ELEMENT_1_MAX        10

#define PAYUEL_CAM_CHILD_TASK_NAME          "PAYUEL_CAM_CHILD"
#define PAYUEL_CAM_CHILD_TASK_STACK_SIZE    16384
#define PAYUEL_CAM_CHILD_TASK_PRIORITY      205
#define PAYUEL_CAM_CHILD_SEM_NAME           "PAYUEL_CAM_SEM"
#define PAYUEL_CAM_CHILD_MUTEX_NAME         "PAY_CAM_CHILD_MUT"
#define PAYUEL_CAM_REPORT_MUTEX_NAME        "PAYUEL_CAM_RPT_MUT"
#define PAYUEL_CAM_HARDWARE_MUTEX_NAME      "PAYUEL_CAM_HW_MUT"

#define PAYUEL_CAM_DOWNLOAD_PATH_MAX        96
#define PAYUEL_CAM_FILE_CRC_BUFFER_SIZE     512

#endif
