#ifndef PAYUEL_CAM_TOPICIDS_H
#define PAYUEL_CAM_TOPICIDS_H

#define CFE_MISSION_PAYUEL_CAM_CMD_TOPICID           0x99
#define CFE_MISSION_PAYUEL_CAM_SEND_BCN_TOPICID      0x9A
#define CFE_MISSION_PAYUEL_CAM_RPT_TLM_TOPICID       0x9B
#define CFE_MISSION_PAYUEL_CAM_BCN_TLM_TOPICID       0x9C

#endif
