#ifndef PAYUEL_CAM_MSGIDS_H
#define PAYUEL_CAM_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "payuel_cam_topicids.h"

#define PAYUEL_CAM_CMD_MID            CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUEL_CAM_CMD_TOPICID)
#define PAYUEL_CAM_SEND_BCN_MID       CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_PAYUEL_CAM_SEND_BCN_TOPICID)

#define PAYUEL_CAM_BCN_TLM_MID        CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUEL_CAM_BCN_TLM_TOPICID)
#define PAYUEL_CAM_RPT_TLM_MID        CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_PAYUEL_CAM_RPT_TLM_TOPICID)

#endif
