#ifndef THRUST_MSGIDS_H
#define THRUST_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "thrust_topicids.h"

/* Command MsgIDs */
#define THRUST_CMD_MID         CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_THRUST_CMD_TOPICID)
#define THRUST_SEND_HK_MID     CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_THRUST_SEND_HK_TOPICID)

/* Telemetry MsgIDs */
#define THRUST_HK_TLM_MID      CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_THRUST_HK_TLM_TOPICID)
#define THRUST_STATUS_TLM_MID  CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_THRUST_STATUS_TLM_TOPICID)
#define THRUST_REPORT_TLM_MID  CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_THRUST_REPORT_TLM_TOPICID)

#endif /* THRUST_MSGIDS_H */
