#ifndef THRUST_TOPICIDS_H
#define THRUST_TOPICIDS_H

/* Command topics (SCH/Ground → THRUST) */
#define CFE_MISSION_THRUST_CMD_TOPICID         0x70
#define CFE_MISSION_THRUST_SEND_HK_TOPICID     0x71

/* Telemetry topics (THRUST → Ground) */
#define CFE_MISSION_THRUST_HK_TLM_TOPICID     0x70
#define CFE_MISSION_THRUST_STATUS_TLM_TOPICID 0x71
#define CFE_MISSION_THRUST_REPORT_TLM_TOPICID 0x72

#endif /* THRUST_TOPICIDS_H */
